### ISSUE TITLE
No "-v" option with asadm.py

### ISSUE THREAD

**Issue by shakthimaan** [aerospike/aerospike-admin#31]
From commit 60218cbf61b0ac4a75824e6f6c713d6415c5a842, when the health check is executed, it concludes with the line:
```
INFO: Please use -v option for more details on failure. 
```
But, passing "-v" throws an error saying:
```
asadm.py: error: unrecognized arguments: -v
```
The "-u" usage option also does not list the "-v" option.

**Comment by hbpatre** [comment]
-v is option of health command, not for asadm. -e is option for asadm which accept command (with its options) as value.
asadm -e "health -v"
