### ISSUE TITLE
Vertical format display option

### ISSUE THREAD

**Issue by shakthimaan** [aerospike/aerospike-admin#32]
Using "show stat" on a cluster of 20 nodes throws the output out of the screen. 

Is it possible to provide a vertical format similar to the "\G" in MySQL command line client?

Reference: https://forums.mysql.com/read.php?108,231614,231614

**Comment by hbpatre** [comment]
"show stat" displays all statistics, if we want to use feature like "\G" in that case we will have lot of columns (one column per stat) in output and it will give same problem even with more columns (>20 nodes).
We have pager feature, so we can scroll vertically and horizontally. Please try this feature.
