### ISSUE TITLE
"pager on" does not work with Mate terminal on Ubuntu

### ISSUE THREAD

**Issue by shakthimaan** [aerospike/aerospike-admin#33]
The "pager on" does not buffer the text properly when using Mate terminal in Ubuntu. 

Pressing 'q' does not quit either. I have to press "Ctrl + c" to break away from the output.

**Comment by hbpatre** [comment]
I tried pager feature on Mate Terminal 1.8.1 in Ubuntu 14.04 and its working on my side.
