### ISSUE TITLE
stuck during collectinfo on _get_awsdata

### ISSUE THREAD

**Issue by felka** [aerospike/aerospike-admin#37]
i3 instance in us-east-1 region 

[INFO] Data collection for _get_awsdata in progress..
 stuck here forever.

**Comment by hbpatre** [comment]
We have already fixed this issue. Those modifications will be published in upcoming release cycle. Temporary solution is to use old asadm version (<= 0.1.8) which is available in aerospike-tools (<= 3.12.0).

Thanks,
Hemant

**Comment by hbpatre** [comment]
This issue is fixed and released in asadm-0.1.12.
