### ISSUE TITLE
asadm -e info creating too many tcp connections

### ISSUE THREAD

**Issue by Entea** [aerospike/aerospike-admin#39]
Hey guys,

I've been trying to use `asadm -e info` output to monitor for `HWM` in a nagios check.
I've noticed that whenever `asadm -e info` is ran, it creates lots of TCP connections. The larger is the cluster, more TCP connections are used and put into `TIME_WAIT` afterwards. This creates an issue if the check is run every minute or so certain services not being able to create new tcp connections.

This is not really a bug (running checks less frequently solves the issue for me) but something that you might consider as an improvement.

**Comment by Entea** [comment]
Okay, the proper way to do it is:
```
telnet localhost 3003
namespace/<name_of_your_namespace
```

Closing the issue :)

**Comment by hbpatre** [comment]
Entea,

Output for `asadm -e info` and telnet command are different. `asadm -e info` command fetches lot of other stats and configs from all nodes. So it creates more connections. If you want to fetch specific information from specific server you can try [asinfo](https://www.aerospike.com/docs/tools/asinfo/index.html) tool.

**Comment by Entea** [comment]
Thanks for explanation @hbpatre!
