### ISSUE TITLE
PI Used total value not showing correctly

### ISSUE THREAD

**Issue by abhilashg1** [aerospike/aerospike-admin#43]
Hi,

Am using `E-5.0.0.10` of Aerospike, when am seeing output of `info` command, the total value of `PI Used` shows zero, might be a logical error in code, please get it fixed in future releases.

Thanks

**Comment by rakeshmaney** [comment]
Thank you Abhilash, this is noted and there is a internal jira filed to fix this.

**Comment by abhilashg1** [comment]
Good to know.
