### ISSUE TITLE
Is there any definitive way of finding out how much memory each bin for a record takes?

### ISSUE THREAD

**Issue by kuskmen** [aerospike/aerospike-admin#46]
Hi guys,
I've been given a task which I am not quite sure what exactly will lead us to but we are still getting familiar with aerospike database and we would like to make some sort of predictions about how much hardware we will need for our operational aerospike database.

I've been asked to determine how much memory each bin in our records takes and I was wondering is there any easy way to do this without actually counting by hand each one of them? Also, the main reason to ask here is to ask if there is a better way of making predictions on how much hardware we will be needing?

Thanks in advance!

**Comment by jdogmcsteezy** [comment]
I can refer you here for capacity planning: https://docs.aerospike.com/docs/operations/plan/capacity/index.html. 

As far as the data + metadata stored with a bin it is dependent on the configuration of the Aerospike database.  Aerospike Academy has a video on this subject if you want to dig deeper. https://academy.aerospike.com/as101-introduction-to-aerospike/299201 @ 3:18
