### ISSUE TITLE
asadm output to console without ansi color codes

### ISSUE THREAD

**Issue by josepowera** [aerospike/aerospike-admin#48]
For a daily report we mail asadm output to email (or log>>file).

However output include colors.   (red for Disk used>50%, blue for summed lines)

Prefered solution: add option to disable  special characters (colors) in asadm output

**Comment by jdogmcsteezy** [comment]
Hey @josepowera, have you tried the `--no-color` flag?  There was an issue with this flag that was fixed in the latest release (asadm 2.7, tools package 7.0)

**Comment by jdogmcsteezy** [comment]
Hey @josepowera, recently I discovered another bug with `--no-color` that will add color codes to the column separators.  This will be fixed in the next release.

**Comment by jdogmcsteezy** [comment]
Look out for tools 7.0.2 and asadm 2.7.2 being released soon.
