### ISSUE TITLE
[aerospike-tools] aql missing dependency

### ISSUE THREAD

**Issue by deric** [aerospike/aerospike-admin#49]
`aql` requires `libreadline7` package which is not listed as dependency:
```
Depends: libc6 (>= 2.7)
```

The latest version ([7.0.0](https://download.aerospike.com/download/tools/notes.html#7.0.0)) claims to add Debian 11 support:
> [TOOLS-1865] - (PACKAGING) Remove support for Debian 8 and add support for Debian 11.

However Debian 11 is shipped with `libreadline8`
```
ldd /usr/bin/aql
        linux-vdso.so.1 (0x00007ffcde3dc000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f52ba599000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f52ba455000)
        libreadline.so.7 => not found
        libhistory.so.7 => not found
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f52ba44a000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f52ba444000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f52ba425000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f52ba260000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f52baa7b000)
```
It should work fine on Debian 10.

[TOOLS-1865]: https://aerospike.atlassian.net/browse/TOOLS-1865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by deric** [comment]
@jdogmcsteezy Thanks, I was looking for `aerospike-tools` repository and I couldn't find one.

**Comment by jdogmcsteezy** [comment]
@deric, no worries.  Glad it sorted itself out.  

Yes, the aerospike-tools package is not something we make public. The only tool in the "Tools package" that was not public was aql.  That is resolved.
